---
date: "2020-11-7"
description: Projects
title: Side Projects
---

**Tidy Tuesday Submissions**  
**Languages**: R  
[[Source Code](https://github.com/qpmnguyen/qn_tidytuesday)]   
Most recent tweet:  
```{r, echo=FALSE, warning=FALSE, message=FALSE, height = 2, width = 2, units = "in"}
#library(rtweet)
#library(dplyr)
#keys <- read.csv(file = "../twitter.txt", header = F)
#token <- create_token(app = "tidy_tuesday_qn", consumer_key = keys %>% filter(V1 == "APIkey") %>% pull(V2),
#                      consumer_secret = keys %>% filter(V1 == "APIsecretkey") %>% pull(V2))
blogdown::shortcode("tweet", "1355577536256815104")
```

Code and graphs for Tidy Tuesday submissions. Tidy Tuesday is a weekly online event hosted by the R4DS community to promote usage of R in data wrangling and visualization. Every week a new data set is distributed where participants are welcome to perform modelling, wranging and visualization.  

**Forecasting presidential elections using Elo rankings**  
**Languages**: Julia, R  
[[Source Code](https://github.com/qpmnguyen/elo_presidente)] [[Pluto.jl](https://mybinder.org/v2/gh/fonsp/pluto-on-binder/master?urlpath=pluto/open?url=https%253A%252F%252Fgithub.com%252Fqpmnguyen%252Felo_presidente%252Fblob%252Fmaster%252Fanalysis.jl%253Fraw%253Dtrue)]
[[Write up](https://limit-testing.netlify.app/posts/2021-01-10-election-prediction-using-elo/)]  
In this project, I explore using probability models based on Elo rankings (rankings used in zero-sum games such as chess) as a way to predict US presidential elections. I extract weekly polling data from FiveThirtyEight as well as results from the 2016 elections to form the basis of the model. Elo gains and losses are allocated per week based on whether a candidate has more than 50% approval in a certain state. These scores are scaled to the margin of victory. An interactive Pluto.jl notebook is provided for the Julia Implementation.